import Head from 'next/head';
import Nav from '../components/Nav';

export default function History() {
	return (
		<div>
			<Head>
				<title>Gym Tracker</title>
				<meta
					name='description'
					content='Generated by create next app'
				/>
				<link rel='icon' href='/favicon.ico' />
			</Head>

			<main className='py-4 px-4 lg:py-10 lg:px-10 w-full'>
				<Nav />
				<section className='flex justify-center'>
					<div className='px-4 py-2 border rounded-lg w-full lg:w-2/4'>
						<div className='border-b h-8 mb-4'>
							<h3 className='text-gray-700'>History</h3>
						</div>
						<ul>
							<li className='h-auto border rounded-sm px-4 py-2 mb-2'>
								<p className='text-sm text-gray-500 mb-2'>
									Lorem ipsum dolor sit amet, consectetur
									adipisicing elit. Repellendus illo deleniti
									voluptas placeat, id dicta, alias ut eos
									quidem necessitatibus omnis est minus nisi.
									Placeat voluptas repellendus culpa
									praesentium iste!
								</p>
								<p className='text-xs text-gray-500 mb-2'>
									2022 -04 - 09
								</p>
							</li>
							<li className='h-auto border rounded-sm px-4 py-2 mb-2'>
								<p className='text-sm text-gray-500 mb-2'>
									Lorem ipsum dolor sit amet, consectetur
									adipisicing elit. Repellendus illo deleniti
									voluptas placeat, id dicta, alias ut eos
									quidem necessitatibus omnis est minus nisi.
									Placeat voluptas repellendus culpa
									praesentium iste!
								</p>
								<p className='text-xs text-gray-500 mb-2'>
									2022 -04 - 09
								</p>
							</li>
							<li className='h-auto border rounded-sm px-4 py-2 mb-2'>
								<p className='text-sm text-gray-500 mb-2'>
									Lorem ipsum dolor sit amet, consectetur
									adipisicing elit. Repellendus illo deleniti
									voluptas placeat, id dicta, alias ut eos
									quidem necessitatibus omnis est minus nisi.
									Placeat voluptas repellendus culpa
									praesentium iste!
								</p>
								<p className='text-xs text-gray-500 mb-2'>
									2022 -04 - 09
								</p>
							</li>
						</ul>
					</div>
				</section>
			</main>
		</div>
	);
}
