import Head from 'next/head';
import Nav from '../components/Nav';

export default function Home() {
	return (
		<div>
			<Head>
				<title>Gym Tracker</title>
				<meta
					name='description'
					content='Generated by create next app'
				/>
				<link rel='icon' href='/favicon.ico' />
			</Head>

			<main className='py-4 px-4 lg:py-10 lg:px-10 w-full'>
				<Nav />
				<section className='flex justify-center'>
					<div className='px-4 py-2 border rounded-lg w-full lg:w-2/4'>
						<div className='border-b h-8 mb-4'>
							<h3 className='text-gray-700'>Gym Tracker</h3>
						</div>
						<form action=''>
							<fieldset>
								<label className='text-sm text-gray-400 mb-2 block'>
									Description
								</label>
								<textarea
									name=''
									id=''
									rows='5'
									className='border w-full rounded-sm mb-6'
								/>
							</fieldset>
							<button className='text-sm text-white px-8 py-2 rounded-sm bg-teal-600 hover:bg-teal-700'>
								Submit
							</button>
						</form>
					</div>
				</section>
			</main>
		</div>
	);
}
