import Head from 'next/head';
import { useState } from 'react';
import Nav from '../components/Nav';
import { createTrack } from '../components/services';

export default function Home() {
	const [description, setDescription] = useState('');
	const [isLoading, setIsloading] = useState(false);

	const handleSubmit = (e) => {
		setIsloading(true);
		e.preventDefault();
		createTrack(description)
			.then((resp) => {
				alert('Tracker created successfully!');
				setDescription('');
				setIsloading(false);
			})
			.catch((e) => {
				alert('Error creating tracker!');
				setIsloading(false);
			});
	};
	return (
		<div>
			<Head>
				<title>Gym Tracker</title>
				<meta
					name='description'
					content='Generated by create next app'
				/>
				<link rel='icon' href='/favicon.ico' />
			</Head>

			<main className='py-4 px-4 lg:py-10 lg:px-10 w-full'>
				<Nav />
				<section className='flex justify-center'>
					<div className='px-4 py-2 border rounded-lg w-full lg:w-2/4'>
						<div className='border-b h-8 mb-4'>
							<h3 className='text-gray-700'>Gym Tracker</h3>
						</div>
						<form onSubmit={handleSubmit}>
							<fieldset>
								<label className='text-sm text-gray-400 mb-2 block'>
									Description
								</label>
								<textarea
									name=''
									id=''
									rows='5'
									className='border w-full rounded-sm mb-6 p-2'
									required
									value={description}
									onChange={(e) =>
										setDescription(e.target.value)
									}
								/>
							</fieldset>
							<button
								className='text-sm text-white px-8 py-2 rounded-sm bg-teal-600 hover:bg-teal-700'
								disabled={isLoading}
							>
								Submit
							</button>
						</form>
					</div>
				</section>
			</main>
		</div>
	);
}
